/*
Created by: Zachary Young
Created on: 07/01/2021
Last edited: 07/03/2021
Created for: CMSC495

MySQL

Ensure the following are applied:
- AWS account differs from MySQL account and from Application account

Objectives
  - Secure MySQL instance, Databases and Tables
  - Create new users that can query applicaiton database
  - Lock down new user permissions
  - Create new applicaiton database
  - Create 4 tables: Users, Inventory, Order History, and App Passwords
  
*/

/* Setup and harden SQL instance */

-- show current databases and users
SHOW databases;
SELECT user FROM mysql.user;
USE mysql;

-- create database for the app
CREATE DATABASE inventory_app_data;
SHOW databases;

-- create users for database
CREATE USER 'inventory_admin'@'localhost' IDENTIFIED BY 'password';
CREATE USER 'inventory_user'@'localhost' IDENTIFIED BY 'password';
SELECT user FROM mysql.user;


-- remove user ability to query any database
SHOW GRANTS FOR 'inventory_admin'@'localhost'; 
SHOW GRANTS FOR 'inventory_user'@'localhost'; 
REVOKE ALL PRIVILEGES ON %database_name% FROM 'inventory_admin'@'localhost'; 
REVOKE ALL PRIVILEGES ON %database_name% FROM 'inventory_user'@'localhost'; 
SHOW GRANTS FOR 'inventory_admin'@'localhost'; 
SHOW GRANTS FOR 'inventory_user'@'localhost'; 

-- GRANT inventory_admin for the inventory_app_data database
GRANT ALL PRIVILEGES ON %database_name% TO 'inventory_admin'@'localhost';

-- GRANT inventory_user for inventory_app_data database
GRANT ALL PRIVILEGES ON %database_name% TO 'inventory_user'@'localhost';

-- check permission of users
SHOW GRANTS FOR 'inventory_admin'@'localhost';
SHOW GRANTS FOR 'inventory_user'@'localhost';


/* Build tables */
-- User application table
-- Role: 0 = admin, 1 = approver, 2 = employee
CREATE TABLE users(
    UserID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
    Username VARCHAR2(60) UNIQUE NOT NULL, 
    Fname VARCHAR2(60) NOT NULL, 
    Lname VARCHAR2(60) NOT NULL,
    Role NUMBER NOT NULL CHECK LIKE (0,1,2) DEFAULT 2
);

COMMENT ON TABLE users IS 'The users table is used for managing application users.';

-- password table referencing user

-- Inventory table
CREATE TABLE inventory(
    InventoryID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
    Name VARCHAR2(60) UNIQUE NOT NULL,  
    Description VARCHAR2(120) UNIQUE NOT NULL, 
    Price DECIMAL(8,2) NOT NULL, 
    Quantity NUMBER NOT NULL
);

COMMENT ON TABLE inventory IS 'The inventory table is used for managing inventory items.';

-- Purchase Order table
CREATE TABLE orders(
    OrderID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, 
    EmployeeID NUMBER UNIQUE NOT NULL,
    ItemID NUMBER UNIQUE NOT NULL,
    Description VARCHAR2(120) UNIQUE NOT NULL, 
    UnitPrice DECIMAL(8,2) NOT NULL,
    TotalPrice DECIMAL(10,2) NOT NULL,
    Quantity NUMBER NOT NULL, 
    OrderDate DATETIME NOT NULL,
    Status NUMBER NOT NULL CHECK LIKE (0,1) DEFAULT 0,
    FOREIGN KEY (EmployeeID) REFERENCES users(UserID),
    FOREIGN KEY (ItemID) REFERENCES inventory(InventoryID)
);

COMMENT ON TABLE inventory IS 'The inventory table is used for managing inventory items.';
