/*
 * File: OrderPanel.java
 * Author: Ben Sutter
 * Date: July 19th, 2021
 * Purpose: Panel that is used in the order subtab
 */
package SIMS;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class OrderPanel extends javax.swing.JPanel {

	public OrderPanel() {
		initComponents();
	}

	private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {

		javax.swing.JTable orderedItems = orderAndSalesPanel.orderTable;
		Map<String, Integer> itemNum = Database.getItemIdMap();

		List<List> databBaseInfo = new ArrayList<List>();

		if (orderedItems.getRowCount() == 0) {
			GeneralGuiFunctions.displayErrorPane("Please select an item to order");

		} else {

			for (int i = 0; i < orderedItems.getRowCount(); i++) {

				// 2D List to pass to createOrder
				List<Object> list = new ArrayList<Object>();

				// int employeeID = ;
				Object itemID = itemNum.get(orderedItems.getValueAt(i, 0));
				System.out.println(itemID);
				// double salesTax =;
				// double wholeSalePrice = ;
				Object quantity = GeneralGuiFunctions.castObjectToInteger(orderedItems.getValueAt(i, 1));
			
				System.out.println(quantity);
				// String date = ;
				// int status = ;

				// list.add(employeeID);
				list.add(itemID);
				// list.add(saleTax);
				// list.add(wholeSalePrice);
				list.add(quantity);
				// list.add(date);
				// list.add(status);

				databBaseInfo.add(list);

				//System.out.println(databBaseInfo);

			} // end for

		} // end else

		// Database.getConnector().createOrder(employeeID, itemID, saleTax,
		// wholeSalePrice, quantity, date, status);

	}// end orderButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private SIMS.OrderAndSalesPanel orderAndSalesPanel;
	public javax.swing.JButton orderButton;
	private javax.swing.JPanel panel;
	// End of variables declaration//GEN-END:variables

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        orderAndSalesPanel = new SIMS.OrderAndSalesPanel();
        orderButton = new javax.swing.JButton();

        orderButton.setBackground(new java.awt.Color(0, 102, 0));
        orderButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        orderButton.setText("Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderAndSalesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderAndSalesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>  

}
